# Generated by Django 5.2.8 on 2025-11-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Start',
            new_name='start',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default='2025-11-14'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='uid',
            field=models.CharField(default='0'),
            preserve_default=False,
        ),
    ]
