# Generated by Django 5.2.8 on 2025-11-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcal', '0002_rename_date_day_date_rename_start_event_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
