# Generated by Django 5.2.8 on 2025-11-15 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventcal', '0003_alter_event_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
    ]
