# Generated by Django 5.2.8 on 2026-02-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcal', '0004_delete_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarconfig',
            name='url',
            field=models.CharField(max_length=200, verbose_name=''),
        ),
    ]
